enum ARCHIVE_ERROR
{
    ARCHIVE_SUCCESS,
    ARCHIVE_CREATION_ERROR,
    ARCHIVE_FORMAT_ERROR,
    ARCHIVE_OPEN_ERROR,
    ARCHIVE_ENTRY_READ_ERROR,
    ARCHIVE_ENTRY_WRITE_ERROR
};

enum FILE_ERROR
{
    FILE_SUCCESS,
    FILE_OPEN_ERROR
};